### ISSUE TITLE
v1.0 Web Service Breaking Due to Outdated Packages

### ISSUE THREAD

**Issue by PantherHawk** [ThreeDotsLabs/wild-workouts-go-ddd-example#64]
I was seeing this error when running the Vue frontend in v1.0, 

```
M; 299 96 9313

C; 685 36 0135

 web_1             |  error  in ./src/main.js
web_1             |
web_1             | Module build failed (from ./node_modules/babel-loader/lib/index.js):
web_1             | Error: [BABEL] /web/src/main.js: Cannot find module '/web/node_modules/@babel/preset-env/node_modules/@babel/compat-data/data/corejs3-shipped-proposals' (While processing: "/web/node_modules/@vue/cli-plugin-babel/preset.js")
web_1             |     at createEsmNotFoundErr (internal/modules/cjs/loader.js:842:15)
web_1             |     at finalizeEsmResolution (internal/modules/cjs/loader.js:835:15)
web_1             |     at resolveExports (internal/modules/cjs/loader.js:424:14)
web_1             |     at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
web_1             |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
web_1             |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
web_1             |     at Module.require (internal/modules/cjs/loader.js:887:19)
web_1             |     at require (internal/modules/cjs/helpers.js:74:18)
web_1             |     at Object.<anonymous> (/web/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
web_1             |     at Module._compile (internal/modules/cjs/loader.js:999:30)
web_1             |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
web_1             |     at Module.load (internal/modules/cjs/loader.js:863:32)
web_1             |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
web_1             |     at Module.require (internal/modules/cjs/loader.js:887:19)
web_1             |     at require (internal/modules/cjs/helpers.js:74:18)
web_1             |     at Object.<anonymous> (/web/node_modules/@babel/preset-env/lib/index.js:29:44)
web_1             |
web_1             |  @ multi (webpack)-dev-server/client/index.js (webpack)/hot/dev-server.js ./src/main.js
```

But I was able to get it running with the following,

```
diff --git a/web/package.json b/web/package.json
index 4f686c9..45c644c 100644
--- a/web/package.json
+++ b/web/package.json
@@ -8,6 +8,7 @@
     "lint": "vue-cli-service lint"
   },
   "dependencies": {
+    "@babel/compat-data": "^7.9.0",
     "@fullcalendar/core": "^4.4.0",
     "@fullcalendar/daygrid": "^4.4.0",
     "@fullcalendar/interaction": "^4.4.0",
@@ -15,7 +16,7 @@
     "@fullcalendar/timegrid": "^4.4.0",
     "@fullcalendar/vue": "^4.4.0",
     "bootstrap": "^4.4.1",
-    "core-js": "^3.6.4",
+    "core-js": "3.27.2",
     "firebase": "^7.14.0",
     "firebase-auth": "^0.1.2",
     "jquery": "^3.4.1",
```

**Comment by m110** [comment]
Has been updated since, thanks. :)
